[package]
name = "libnastran-cp36"
version = "0.1.0"
authors = ["Andrew Burkett <burkett.andrew@gmail.com>"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module","python-3-6"]

[dependencies]
nastran = { path = ".." }

[lib]
crate-type = ["cdylib"]
