[package]
name = "naspy"
version = "0.1.0"
authors = ["Andrew Burkett <burkett.andrew@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
nastran = { path = ".." }

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]

