[package]
name = "libnastran"
version = "0.1.0"
authors = ["Andrew Burkett <burkett.andrew@gmail.com>"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]

[dependencies]
nastran = { path = ".." }

[lib]
crate-type = ["cdylib"]
